---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
spec:
  interval: 5m
  url: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
  ref:
    tag: 2.0.2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-gateway
  namespace: nginx-gateway
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: nginx-gateway
  values:
    nginx:
      service:
        type: NodePort
        nodePorts:
          - port: 30080
            listenerPort: 80
