---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops
spec:
  generators:
    - git:
        directories:
          - path: npr/*
        repoURL: https://github.com/zasdaym/gitops.git
        revision: HEAD
  goTemplate: true
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      destination:
        namespace: '{{.path.basename}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        path: '{{.path.path}}'
        repoURL: https://github.com/zasdaym/gitops.git
        targetRevision: HEAD
      syncPolicy:
        automated: {}
        syncOptions:
          - CreatedNamespace=true
