namespace: argocd
resources:
  - namespace.yaml
  - applicationset.yaml
helmCharts:
  - includeCRDs: true
    name: argo-cd
    namespace: argocd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    version: 7.7.5
    valuesInline:
      applicationSet:
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
      configs:
        cm:
          create: true
          kustomize.buildOptions: --enable-helm
        params:
          "server.insecure": true
      controller:
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
      dex:
        enabled: false
      global:
        domain: argocd.zasdaym.my.id
      notifications:
        enabled: false
      redis:
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
      repoServer:
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
      server:
        ingress:
          enabled: true
          ingressClassName: nginx
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
