---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: haproxy
  namespace: haproxy
spec:
  interval: 5m
  url: oci://ghcr.io/haproxytech/helm-charts/kubernetes-ingress
  ref:
    semver: 1.44.1
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy
  namespace: haproxy
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: haproxy
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      kubernetesGateway:
        enabled: true
      service:
        nodePorts:
          http: 31080
