namespace: local-path-provisioner
resources:
  - namespace.yaml
helmCharts:
  - name: local-path-provisioner
    repo: https://charts.containeroo.ch
    version: 0.0.37
    releaseName: local-path-provisioner
    namespace: local-path-provisioner
    valuesFile: values.yaml
