image:
  repository: docker.io/rancher/local-path-provisioner
  tag: v0.0.36

helperImage:
  repository: docker.io/library/busybox
  tag: 1.37.0

storageClass:
  create: true
  defaultClass: false
  defaultVolumeType: hostPath
  name: local-path
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}/"

nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths:
      - /srv

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 128Mi

helperPod:
  resources:
    requests:
      cpu: 10m
      memory: 16Mi
    limits:
      memory: 32Mi
