---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  labels:
    component: server
spec:
  template:
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v1.132.3
          envFrom:
            - configMapRef:
                name: immich-server
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: /usr/src/app/upload
              readOnly: false
      volumes:
        - name: data
          hostPath:
            path: /srv/immich
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: immich-server
  labels:
    component: server
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 80
      targetPort: 2283
