namespace: node-exporter
resources:
  - namespace.yaml
helmCharts:
  - name: prometheus-node-exporter
    repo: https://prometheus-community.github.io/helm-charts
    version: 4.56.1
    releaseName: node-exporter
    namespace: node-exporter
    valuesFile: values.yaml
