apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: VictoriaMetrics
      type: prometheus
      access: proxy
      url: http://victoriametrics.victoriametrics.svc.cluster.local:8428
      isDefault: true
      editable: false
      jsonData:
        httpMethod: GET
    - name: VictoriaLogs
      type: victoriametrics-logs-datasource
      access: proxy
      url: http://victorialogs.victorialogs.svc.cluster.local:9428
      editable: false
      jsonData:
        maxLines: 1000