apiVersion: 1
prune: true
datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: http://vmselect-victoriametrics.victoriametrics.svc.cluster.local:8481/select/0/prometheus
    isDefault: true
    editable: false
    jsonData:
      httpMethod: GET
  - name: VictoriaLogs
    uid: victorialogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://vlselect-victorialogs.victorialogs.svc.cluster.local:9471/select
    editable: false
    jsonData:
      maxLines: 1000
