namespace: grafana
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: grafana
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- datasources.yaml
- ingress.yaml
