namespace: grafana
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: grafana
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
configMapGenerator:
- name: grafana-datasources
  files:
  - datasources.yaml
- name: grafana-dashboard-provider
  files:
  - dashboard-provider.yaml
- name: grafana-dashboard-node-exporter
  files:
  - node-exporter.json=dashboards/node-exporter.json
