apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      hostAPI: https://app.infisical.com
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical
            namespace: external-secrets
            key: clientId
          clientSecret:
            name: infisical
            namespace: external-secrets
            key: clientSecret
      secretsScope:
        projectSlug: default-4634
        environmentSlug: staging
        secretsPath: /
        recursive: true
