apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalAuth
metadata:
  name: infisical
spec:
  infisicalConnectionRef:
    name: infisical
    namespace: infisical
  method: universal
  universal:
    clientIdRef:
      name: infisical
      namespace: infisical
      key: clientId
    clientSecretRef:
      name: infisical
      namespace: infisical
      key: clientSecret
