---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: infisical
  namespace: infisical
spec:
  interval: 5m
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: infisical
spec:
  interval: 5m
  chart:
    spec:
      chart: secrets-operator
      version: v0.10.6
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: infisical
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
