namespace: infisical
resources:
  - namespace.yaml
  - connection.yaml
  - auth.yaml
helmCharts:
  - name: secrets-operator
    repo: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts
    version: 0.11.8
    releaseName: infisical
    namespace: infisical
    includeCRDs: true
    valuesFile: values.yaml
