apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: alloy
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      containers:
      - name: alloy
        image: grafana/alloy:v1.10.2
        args:
        - run
        - /etc/alloy/config.alloy
        - --storage.path=/tmp/alloy
        - --server.http.listen-addr=0.0.0.0:12345
        - --cluster.enabled=false
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 12345
          name: http-metrics
        volumeMounts:
        - name: config
          mountPath: /etc/alloy
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: containerd
          mountPath: /run/containerd/containerd.sock
          readOnly: true
        securityContext:
          privileged: true
          runAsUser: 0
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            memory: 1Gi
      volumes:
      - name: config
        configMap:
          name: alloy-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: containerd
        hostPath:
          path: /run/k0s/containerd.sock
      hostNetwork: false
      hostPID: true
