namespace: caddy
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: caddy
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - httproute.yaml
