apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.11.3
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      hostPort:
        enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      service:
        enabled: false
