namespace: observability
resources:
  - namespace.yaml
  - vmcluster.yaml
  - vlcluster.yaml
  - vmagent.yaml
  - node-exporter-scrape.yaml
  - vlagent.yaml
helmCharts:
  - name: victoria-metrics-operator
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.67.2
    releaseName: vmo
    namespace: observability
    includeCRDs: true
    valuesFile: operator-values.yaml
