nameOverride: vmo

crds:
  enabled: true
  plain: true

operator:
  disable_prometheus_converter: true

admissionWebhooks:
  enabled: false

resources:
  requests:
    memory: 128Mi
  limits:
    memory: 256Mi
