apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: victoriametrics
spec:
  clusterVersion: v1.148.0-cluster
  retentionPeriod: 31d
  replicationFactor: 1
  vminsert:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 1Gi
  vmselect:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 1Gi
  vmstorage:
    replicaCount: 1
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 1Gi
