---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
spec:
  interval: 5m
  url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
  ref:
    tag: 6.3.0
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: kube-state-metrics
  values:
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8080"
      prometheus.io/metrics: "/metrics"
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
