namespace: kube-state-metrics
resources:
  - namespace.yaml
helmCharts:
  - name: kube-state-metrics
    repo: oci://ghcr.io/prometheus-community/charts
    version: 6.3.0
    releaseName: kube-state-metrics
    namespace: kube-state-metrics
    includeCRDs: true
    valuesFile: values.yaml
