apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victorialogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victorialogs
  template:
    metadata:
      labels:
        app: victorialogs
    spec:
      containers:
        - name: victorialogs
          image: victoriametrics/victoria-logs:v1.32.0
          args:
            - "-storageDataPath=/storage"
            - "-retentionPeriod=1w"
          ports:
            - containerPort: 9428
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi
          volumeMounts:
            - name: storage
              mountPath: /storage
      volumes:
        - name: storage
          hostPath:
            path: /srv/victorialogs/data
            type: DirectoryOrCreate
