apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: postgres
    creationPolicy: Orphan
  dataFrom:
    - find:
        name:
          regexp: .*
        path: /postgres
