apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: postgres
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /postgres/POSTGRES_PASSWORD
  dataFrom:
    - find:
        name:
          regexp: .*
        path: /postgres
