apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: postgres
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical
        secretNamespace: infisical
      secretsScope:
        envSlug: staging
        recursive: true
        secretsPath: /postgres
  managedKubeSecretReferences:
    - secretName: postgres
      secretNamespace: postgres
