namespace: postgres
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: postgres
resources:
  - namespace.yaml
  - infisicalsecret.yaml
  - service.yaml
  - statefulset.yaml
