namespace: postgres
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: postgres
resources:
  - namespace.yaml
  - password.yaml
  - pushsecret.yaml
  - externalsecret.yaml
  - service.yaml
  - statefulset.yaml
