apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: postgres
spec:
  refreshInterval: 1m
  updatePolicy: IfNotExists
  deletionPolicy: None
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: infisical
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: postgres
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: /postgres/POSTGRES_PASSWORD
