apiVersion: secrets.infisical.com/v1beta1
kind: InfisicalStaticSecret
metadata:
  name: postgres
spec:
  infisicalAuthRef:
    name: infisical
    namespace: infisical
  syncOptions:
    refreshInterval: 60s
  sources:
    - projectId: bb92c750-e92a-4499-b2c4-e2e9fc3d407b
      environmentSlug: staging
      secretPath: /postgres
      recursive: true
  targets:
    - name: postgres
      namespace: postgres
      kind: Secret
      creationPolicy: Orphan
