---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pdack
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pdack
              image: ghcr.io/zasdaym/pdack:v1.0.6
              envFrom:
                - configMapRef:
                    name: pdack
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  memory: 128Mi
          imagePullSecrets:
            - name: github
          restartPolicy: OnFailure
