apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: victoriametrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      containers:
        - name: victoriametrics
          image: victoriametrics/victoria-metrics:v1.125.1
          args:
            - "--storageDataPath=/storage"
            - "--retentionPeriod=31d"
          ports:
            - containerPort: 8428
              name: http
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi
          volumeMounts:
            - name: storage
              mountPath: /storage
      volumes:
        - name: storage
          hostPath:
            path: /srv/victoriametrics/data
            type: DirectoryOrCreate
